'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowRight, Youtube } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { extractVideoId, isValidYouTubeUrl } from '@/lib/utils';
import { useAuthStore } from '@/store/authStore';
import HeroImage from '@/components/HeroImage';
import SummaryCard from '@/components/SummaryCard';

// Sample data for the summary card
const sampleSummary = {
  title: 'How to use LLMs?',
  date: '2025-03-03',
  channelName: 'Andrej Karpathy channel',
  isSubscribed: false,
  summary:
    'This is a sample summary text. It would contain the key points from the video, including main ideas, examples, and conclusions. The summary would be generated by our AI to provide value to users without them having to watch the entire video.',
  tags: ['LLMs', 'Machine Learning', 'AI'],
  peopleMentioned: ['Andrej Karpathy', 'Geoffrey Hinton', 'Yann LeCun'],
  videoId: 'sample-video-id',
};

export default function Home() {
  const [url, setUrl] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const router = useRouter();
  const { user } = useAuthStore();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!url.trim()) {
      setError('Please enter a YouTube URL');
      return;
    }

    if (!isValidYouTubeUrl(url)) {
      setError('Please enter a valid YouTube URL');
      return;
    }

    setIsLoading(true);
    const videoId = extractVideoId(url);

    if (videoId) {
      router.push(`/summary/${videoId}`);
    } else {
      setError('Could not extract video ID from URL');
      setIsLoading(false);
    }
  };

  return (
    <main className='flex flex-col min-h-[calc(100vh-64px)]'>
      {/* Hero Section */}
      <section className='flex-1 flex flex-col lg:flex-row px-4 md:px-6 pt-8 pb-12 md:pt-12 md:pb-24 bg-gradient-to-br from-blue-50 to-purple-50'>
        <div className='flex-1 flex flex-col justify-center max-w-3xl mx-auto lg:mx-0 text-center lg:text-left'>
          <h1 className='text-4xl md:text-5xl lg:text-6xl font-bold text-gray-900 mb-6'>
            Get <span className='text-[#4263eb]'>Smart</span> with YouTube Content
          </h1>
          <p className='text-xl text-gray-600 mb-8 md:pr-12'>
            Transform lengthy videos into concise, digestible summaries. Save time and extract key
            insights in seconds.
          </p>

          <form onSubmit={handleSubmit} className='w-full max-w-2xl mx-auto lg:mx-0 mb-8'>
            <div className='flex flex-col sm:flex-row gap-4'>
              <div className='relative flex-1'>
                <div className='absolute left-3 top-1/2 -translate-y-1/2 text-gray-400'>
                  <Youtube size={20} />
                </div>
                <Input
                  type='text'
                  placeholder='Paste YouTube URL'
                  value={url}
                  onChange={e => setUrl(e.target.value)}
                  className='pl-10 h-12 bg-white border-gray-200 focus:border-[#4263eb] focus:ring-[#4263eb]'
                />
              </div>
              <Button
                type='submit'
                disabled={isLoading}
                className='h-12 px-6 bg-[#4263eb] hover:bg-[#3b5bdb] text-white'>
                {isLoading ? 'Processing...' : 'Summarize'}
                {!isLoading && <ArrowRight className='ml-2 h-4 w-4' />}
              </Button>
            </div>
            {error && <p className='mt-2 text-red-500 text-sm'>{error}</p>}
          </form>

          <div className='flex flex-wrap justify-center lg:justify-start gap-4 mt-2'>
            <Link href={user ? '/discover' : '/signup'}>
              <Button variant='outline' className='border-gray-200 hover:bg-gray-50'>
                {user ? 'Discover Content' : 'Create Free Account'}
                <ArrowRight className='ml-2 h-4 w-4' />
              </Button>
            </Link>
            <Link href='/about'>
              <Button
                variant='ghost'
                className='text-gray-600 hover:text-[#4263eb] hover:bg-blue-50'>
                Learn More
              </Button>
            </Link>
          </div>
        </div>

        <div className='flex-1 mt-12 lg:mt-0 flex justify-center lg:justify-end items-center'>
          <HeroImage />
        </div>
      </section>

      {/* Summary Card Section */}
      <section className='py-16 px-4 bg-white'>
        <div className='max-w-7xl mx-auto'>
          <div className='flex justify-center'>
            <SummaryCard
              title={sampleSummary.title}
              date={sampleSummary.date}
              channelName={sampleSummary.channelName}
              isSubscribed={sampleSummary.isSubscribed}
              summary={sampleSummary.summary}
              tags={sampleSummary.tags}
              peopleMentioned={sampleSummary.peopleMentioned}
              videoId={sampleSummary.videoId}
            />
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className='py-16 px-4 bg-white'>
        <div className='max-w-7xl mx-auto'>
          <h2 className='text-3xl font-bold text-center mb-12'>Why Choose GetSmart?</h2>

          <div className='grid md:grid-cols-3 gap-8'>
            <div className='bg-gradient-to-br from-blue-50 to-purple-50 p-6 rounded-xl'>
              <div className='w-12 h-12 bg-[#4263eb] rounded-full flex items-center justify-center mb-4'>
                <svg
                  xmlns='http://www.w3.org/2000/svg'
                  width='24'
                  height='24'
                  viewBox='0 0 24 24'
                  fill='none'
                  stroke='white'
                  strokeWidth='2'
                  strokeLinecap='round'
                  strokeLinejoin='round'>
                  <circle cx='12' cy='12' r='10'></circle>
                  <line x1='12' y1='16' x2='12' y2='12'></line>
                  <line x1='12' y1='8' x2='12.01' y2='8'></line>
                </svg>
              </div>
              <h3 className='text-xl font-semibold mb-2'>Save Time</h3>
              <p className='text-gray-600'>
                Get the key points from hour-long videos in just minutes, helping you consume
                content efficiently.
              </p>
            </div>

            <div className='bg-gradient-to-br from-blue-50 to-purple-50 p-6 rounded-xl'>
              <div className='w-12 h-12 bg-[#4263eb] rounded-full flex items-center justify-center mb-4'>
                <svg
                  xmlns='http://www.w3.org/2000/svg'
                  width='24'
                  height='24'
                  viewBox='0 0 24 24'
                  fill='none'
                  stroke='white'
                  strokeWidth='2'
                  strokeLinecap='round'
                  strokeLinejoin='round'>
                  <polygon points='12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2'></polygon>
                </svg>
              </div>
              <h3 className='text-xl font-semibold mb-2'>Enhanced Comprehension</h3>
              <p className='text-gray-600'>
                Our AI extracts the most important information, making complex topics easier to
                understand.
              </p>
            </div>

            <div className='bg-gradient-to-br from-blue-50 to-purple-50 p-6 rounded-xl'>
              <div className='w-12 h-12 bg-[#4263eb] rounded-full flex items-center justify-center mb-4'>
                <svg
                  xmlns='http://www.w3.org/2000/svg'
                  width='24'
                  height='24'
                  viewBox='0 0 24 24'
                  fill='none'
                  stroke='white'
                  strokeWidth='2'
                  strokeLinecap='round'
                  strokeLinejoin='round'>
                  <path d='M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z'></path>
                </svg>
              </div>
              <h3 className='text-xl font-semibold mb-2'>Secure & Private</h3>
              <p className='text-gray-600'>
                Your viewing history and summaries are private and secure, with optional account
                features for saving content.
              </p>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
