name: Schedule Check New Videos

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  trigger-edge-function:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Set a reasonable timeout
    
    steps:
      - name: Trigger Supabase Function
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            --max-time 60 \
            https://ijtwvrzkbnfepbfyfrvc.supabase.co/functions/v1/check-new-videos
      
      - name: Log Success
        if: success()
        run: echo "Successfully triggered check-new-videos function"
      
      - name: Log Failure
        if: failure()
        run: |
          echo "Failed to trigger check-new-videos function"
          echo "Check that CRON_SECRET is correctly set in repository secrets" 