name: Schedule Daily Newsletter

on:
  schedule:
    # Run daily at 3:30 UTC (9:00 IST)
    - cron: '30 3 * * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  trigger-edge-function:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Set a reasonable timeout
    
    steps:
      - name: Trigger Supabase Edge Function
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.SUPABASE_FUNCTION_URL_NEWSLETTER }}
          method: 'POST'
          customHeaders: '{"Authorization": "Bearer ${{ secrets.CRON_SECRET }}", "Content-Type": "application/json"}'
          timeout: 60000  # 60 seconds timeout, matching your function's internal timeout
      
      - name: Log Success
        if: success()
        run: echo "Successfully triggered send-daily-newsletter function"
      
      - name: Log Failure
        if: failure()
        run: |
          echo "Failed to trigger send-daily-newsletter function"
          echo "Check that SUPABASE_FUNCTION_URL_NEWSLETTER and CRON_SECRET are correctly set in repository secrets" 