name: Schedule Daily Newsletter

on:
  schedule:
    # Run daily at 3:30 UTC (9:00 IST)
    - cron: '30 3 * * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  trigger-edge-function:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Set a reasonable timeout
    
    steps:
      - name: Trigger Supabase Function
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            --max-time 60 \
            https://ijtwvrzkbnfepbfyfrvc.supabase.co/functions/v1/send-daily-newsletter
      
      - name: Log Success
        if: success()
        run: echo "Successfully triggered send-daily-newsletter function"
      
      - name: Log Failure
        if: failure()
        run: |
          echo "Failed to trigger send-daily-newsletter function"
          echo "Check that CRON_SECRET is correctly set in repository secrets" 